[graph]
targets = ["bins", "tests", "benches", "examples", "libs"]
exclude = []
all-features = true
no-default-features = false
features = []

[output]
feature-depth = 1

[advisories]
# More info: https://embarkstudios.github.io/cargo-deny/checks/advisories/cfg.html
db-path = ["$CARGO_HOME/advisory-dbs"]
db-urls = ["https://github.com/RustSec/advisory-db"]
ignore = []

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "ISC",
    "MPL-2.0",
    "Zlib"
    # TODO: see about GPL licenses and how this would affect crate usage
]
confidence-threshold = 0.9
exceptions = []

[licenses.private]
ignore = false
registries = []

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = []
deny = []
skip = []
skip-tree = []

[sources]
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []

[sources.allow-org]
github = [""]
gitlab = [""]
bitbucket = [""]
